language: java
env: # allows jobs failures
jdk: oraclejdk11
before_install: chmod +x gradlew
install: skip
stages:
  - compile backend
  - test
  - install frontend
#  - test frontend
  - bootJar
  - deploy to production
jobs:
  include:
    - stage: compile backend
      script: ./gradlew :backend:assemble -x jar -x bootJar
    - stage: bootJar
      script: ./gradlew :backend:bootJar
    - stage: install frontend
      script: ./gradlew :frontend:npm_install
#    - stage: test frontend
#      script: ./gradlew :frontend:npm_test
    - stage: deploy to production
      script: skip
      deploy:
        provider: heroku
        app: omami
        api_key: 2e18c941-6a80-49f0-bd39-9c2c5bb11b74