language: java
env: # allows jobs failures
jdk: oraclejdk11
before_install:
  - chmod +x frontend/gradlew
  - chmod +x backend/gradlew
install: skip
stages:
  - compile backend
  - test
  - install frontend
  - test frontend
  - bootJar
  - deploy to production
jobs:
  include:
    - stage: compile backend
      before_script: cd backend
      script: ./gradlew assemble -x jar -x bootJar
    - stage: bootJar
      before_script: cd backend
      script: ./gradlew bootJar
    - stage: install frontend
      before_script: cd frontend
      script: ./gradlew npm_install
    - stage: test frontend
      before_script: cd frontend
      script: ./gradlew npm_test
    - stage: deploy to production
      script: skip
      deploy:
        provider: heroku
        app: omami
        api_key: 2e18c941-6a80-49f0-bd39-9c2c5bb11b74