CREATE SCHEMA omami
    AUTHORIZATION omami;

COMMENT ON SCHEMA public
    IS 'omami schema fuck yeah!';

GRANT ALL ON SCHEMA omami TO omami;


CREATE TABLE omami.room
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT room_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

CREATE TABLE omami."user"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1),
    login text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT login_constraint UNIQUE (login)

)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

CREATE TABLE omami.message
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1),
    data text COLLATE pg_catalog."default",
    user_id integer NOT NULL,
    room_id integer NOT NULL,
    "time" timestamp NOT NULL,
    CONSTRAINT message_pkey PRIMARY KEY (id),
    CONSTRAINT message_room_id FOREIGN KEY (room_id)
        REFERENCES omami.room (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT message_user_id FOREIGN KEY (user_id)
        REFERENCES omami."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

CREATE TABLE omami.user_room
(
    user_id integer NOT NULL,
    room_id integer NOT NULL,
    CONSTRAINT "user-room-pk" PRIMARY KEY (user_id, room_id),
    CONSTRAINT room_id FOREIGN KEY (room_id)
        REFERENCES omami.room (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT user_id FOREIGN KEY (user_id)
        REFERENCES omami."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

INSERT INTO omami.room(name) VALUES ('Hello omami');

INSERT INTO omami."user"(login, password) VALUES ('omami', 'omami');
INSERT INTO omami."user"(login, password) VALUES ('omamo', 'omamo');

INSERT INTO omami.user_room(user_id, room_id) VALUES (1,1);
INSERT INTO omami.user_room(user_id, room_id) VALUES (2,1);

INSERT INTO omami.message(data, user_id, room_id, time) VALUES ('Hello', 1, 1, '2018-12-12 12:12:12');
INSERT INTO omami.message(data, user_id, room_id, time) VALUES ('Hello !', 2, 1, '2018-12-12 12:12:50');
